import type { TierId } from "./tiers";

export type AnswerDef = {
  /** каноническая форма, которую показываем игроку */
  n: string;
  t: TierId;
  /** синонимы, другие транслитерации, частые написания */
  a?: string[];
};

export type PromptDef = {
  id: string;
  text: string;
  placeholder: string;
  /** список исчерпывает предметную область — короткий банк здесь не изъян */
  exhaustive?: boolean;
  answers: AnswerDef[];
};

export const PROMPTS: PromptDef[] = [
  {
    id: "pisatel",
    text: "Назови писателя",
    placeholder: "назови писателя…",
    answers: [
      { n: "Пушкин", t: "plankton", a: ["александр пушкин"] },
      { n: "Толстой", t: "plankton", a: ["лев толстой"] },
      { n: "Шекспир", t: "plankton" },
      { n: "Достоевский", t: "tooclever" },
      { n: "Кафка", t: "tooclever" },
      { n: "Оруэлл", t: "tooclever" },
      { n: "Булгаков", t: "tooclever" },
      { n: "Гоголь", t: "schooler" },
      { n: "Чехов", t: "schooler" },
      { n: "Диккенс", t: "schooler" },
      { n: "Хемингуэй", t: "schooler" },
      { n: "Марк Твен", t: "schooler" },
      { n: "Джек Лондон", t: "schooler" },
      { n: "Дюма", t: "schooler" },
      { n: "Ремарк", t: "schooler" },
      { n: "Лермонтов", t: "schooler" },
      { n: "Тургенев", t: "schooler" },
      { n: "Гюго", t: "schooler" },
      { n: "Жюль Верн", t: "schooler" },
      { n: "Стивен Кинг", t: "schooler" },
      { n: "Толкин", t: "schooler", a: ["толкиен"] },
      { n: "Оскар Уайльд", t: "schooler", a: ["уайльд"] },
      { n: "Агата Кристи", t: "schooler" },
      { n: "Конан Дойл", t: "schooler", a: ["артур конан дойл"] },
      { n: "Бальзак", t: "rare" },
      { n: "Флобер", t: "rare" },
      { n: "Стендаль", t: "rare" },
      { n: "Сервантес", t: "rare" },
      { n: "Джойс", t: "rare" },
      { n: "Пруст", t: "rare" },
      { n: "Фолкнер", t: "rare" },
      { n: "Борхес", t: "rare" },
      { n: "Стейнбек", t: "rare" },
      { n: "Набоков", t: "rare" },
      { n: "Бунин", t: "rare" },
      { n: "Куприн", t: "rare" },
      { n: "Гессе", t: "rare" },
      { n: "Маркес", t: "rare", a: ["габриэль гарсиа маркес"] },
      { n: "Сэлинджер", t: "rare" },
      { n: "Воннегут", t: "rare" },
      { n: "Камю", t: "rare" },
      { n: "Мопассан", t: "rare" },
      { n: "Золя", t: "rare" },
      { n: "Кортасар", t: "deepcut" },
      { n: "Селин", t: "deepcut" },
      { n: "Музиль", t: "deepcut" },
      { n: "Гамсун", t: "deepcut" },
      { n: "Кальвино", t: "deepcut" },
      { n: "Перек", t: "deepcut" },
      { n: "Бруно Шульц", t: "deepcut" },
      { n: "Платонов", t: "deepcut", a: ["андрей платонов"] },
      { n: "Лесков", t: "deepcut" },
      { n: "Гончаров", t: "deepcut" },
      { n: "Мисима", t: "deepcut" },
      { n: "Кобо Абэ", t: "deepcut" },
      { n: "Павич", t: "deepcut" },
      { n: "Кутзее", t: "deepcut" },
      { n: "Гомбрович", t: "krillion", a: ["витольд гомбрович"] },
      { n: "Краснахоркаи", t: "krillion", a: ["ласло краснахоркаи"] },
    ],
  },
  {
    id: "stolica",
    text: "Назови столицу любой страны",
    placeholder: "назови столицу…",
    answers: [
      { n: "Париж", t: "plankton" },
      { n: "Лондон", t: "plankton" },
      // «я знаю подвох» — столицы, которыми хвастаются чаще всего
      { n: "Оттава", t: "tooclever" },
      { n: "Канберра", t: "tooclever" },
      { n: "Берн", t: "tooclever" },
      { n: "Токио", t: "schooler" },
      { n: "Вашингтон", t: "schooler" },
      { n: "Берлин", t: "schooler" },
      { n: "Рим", t: "schooler" },
      { n: "Мадрид", t: "schooler" },
      { n: "Пекин", t: "schooler" },
      { n: "Каир", t: "schooler" },
      { n: "Москва", t: "schooler" },
      { n: "Вена", t: "schooler" },
      { n: "Прага", t: "schooler" },
      { n: "Варшава", t: "schooler" },
      { n: "Афины", t: "schooler" },
      { n: "Лиссабон", t: "schooler" },
      { n: "Амстердам", t: "schooler" },
      { n: "Брюссель", t: "schooler" },
      { n: "Стокгольм", t: "schooler" },
      { n: "Киев", t: "schooler" },
      { n: "Анкара", t: "schooler" },
      { n: "Дели", t: "schooler", a: ["нью дели"] },
      { n: "Лима", t: "rare" },
      { n: "Ханой", t: "rare" },
      { n: "Найроби", t: "rare" },
      { n: "Хельсинки", t: "rare" },
      { n: "Осло", t: "rare" },
      { n: "Тегеран", t: "rare" },
      { n: "Богота", t: "rare" },
      { n: "Куала-Лумпур", t: "rare", a: ["куала лумпур"] },
      { n: "Сеул", t: "rare" },
      { n: "Бангкок", t: "rare" },
      { n: "Джакарта", t: "rare" },
      { n: "Манила", t: "rare" },
      { n: "Каракас", t: "rare" },
      { n: "Сантьяго", t: "rare" },
      { n: "Бразилиа", t: "rare" },
      { n: "Веллингтон", t: "rare" },
      { n: "Рабат", t: "rare" },
      { n: "Будапешт", t: "rare" },
      { n: "Ташкент", t: "rare" },
      { n: "Астана", t: "rare" },
      { n: "Баку", t: "rare" },
      { n: "Тбилиси", t: "rare" },
      { n: "Ереван", t: "rare" },
      { n: "Претория", t: "deepcut" },
      { n: "Асунсьон", t: "deepcut" },
      { n: "Улан-Батор", t: "deepcut", a: ["улан батор"] },
      { n: "Тирана", t: "deepcut" },
      { n: "Виндхук", t: "deepcut" },
      { n: "Габороне", t: "deepcut" },
      { n: "Тхимпху", t: "deepcut" },
      { n: "Парамарибо", t: "deepcut" },
      { n: "Сукре", t: "deepcut" },
      { n: "Джорджтаун", t: "deepcut" },
      { n: "Банжул", t: "deepcut" },
      { n: "Ломе", t: "deepcut" },
      { n: "Порто-Ново", t: "deepcut", a: ["порто ново"] },
      { n: "Мбабане", t: "deepcut" },
      { n: "Масеру", t: "deepcut" },
      { n: "Вадуц", t: "deepcut", a: ["вадуз"] },
      { n: "Нейпьидо", t: "deepcut" },
      { n: "Уагадугу", t: "deepcut" },
      { n: "Нуакшот", t: "deepcut" },
      { n: "Ямусукро", t: "krillion" },
      { n: "Порт-Морсби", t: "krillion", a: ["порт морсби"] },
    ],
  },
  {
    id: "reka",
    text: "Назови реку",
    placeholder: "назови реку…",
    answers: [
      { n: "Нил", t: "plankton" },
      { n: "Амазонка", t: "plankton" },
      { n: "Волга", t: "tooclever" },
      { n: "Миссисипи", t: "tooclever" },
      { n: "Дунай", t: "schooler" },
      { n: "Темза", t: "schooler" },
      { n: "Сена", t: "schooler" },
      { n: "Янцзы", t: "schooler" },
      { n: "Ганг", t: "schooler" },
      { n: "Рейн", t: "schooler" },
      { n: "Конго", t: "schooler" },
      { n: "Евфрат", t: "schooler" },
      { n: "Тигр", t: "schooler" },
      { n: "Хуанхэ", t: "schooler" },
      { n: "Обь", t: "schooler" },
      { n: "Енисей", t: "schooler" },
      { n: "Лена", t: "schooler" },
      { n: "Дон", t: "schooler" },
      { n: "Амур", t: "schooler" },
      { n: "Нева", t: "schooler" },
      { n: "Днепр", t: "schooler" },
      { n: "Висла", t: "schooler" },
      { n: "Эльба", t: "schooler" },
      { n: "Колорадо", t: "schooler" },
      { n: "Миссури", t: "rare" },
      { n: "Меконг", t: "rare" },
      { n: "Замбези", t: "rare" },
      { n: "Ориноко", t: "rare" },
      { n: "Инд", t: "rare" },
      { n: "Луара", t: "rare" },
      { n: "Юкон", t: "rare" },
      { n: "Парана", t: "rare" },
      { n: "Муррей", t: "rare" },
      { n: "Нигер", t: "rare" },
      { n: "Иртыш", t: "rare" },
      { n: "Печора", t: "rare" },
      { n: "Колыма", t: "rare" },
      { n: "Рона", t: "rare" },
      { n: "Гаронна", t: "rare" },
      { n: "Эбро", t: "rare" },
      { n: "Брахмапутра", t: "rare" },
      { n: "Ангара", t: "rare" },
      { n: "Ока", t: "rare" },
      { n: "По", t: "rare" },
      { n: "Лимпопо", t: "deepcut" },
      { n: "Иравади", t: "deepcut" },
      { n: "Огове", t: "deepcut" },
      { n: "Маккензи", t: "deepcut" },
      { n: "Тежу", t: "deepcut", a: ["тахо"] },
      { n: "Дрина", t: "deepcut" },
      { n: "Марица", t: "deepcut" },
      { n: "Северная Двина", t: "deepcut" },
      { n: "Вычегда", t: "deepcut" },
      { n: "Мезень", t: "deepcut" },
      { n: "Сава", t: "deepcut" },
      { n: "Тиса", t: "deepcut" },
      { n: "Одра", t: "deepcut", a: ["одер"] },
      { n: "Салуин", t: "deepcut" },
      { n: "Шари", t: "deepcut" },
      { n: "Шелифф", t: "krillion" },
    ],
  },
  {
    id: "rok",
    text: "Назови рок-группу",
    placeholder: "назови группу…",
    answers: [
      { n: "The Beatles", t: "plankton", a: ["битлз", "beatles"] },
      { n: "Queen", t: "plankton", a: ["куин"] },
      { n: "Nirvana", t: "tooclever", a: ["нирвана"] },
      { n: "Pink Floyd", t: "tooclever", a: ["пинк флойд"] },
      { n: "Led Zeppelin", t: "schooler", a: ["лед зеппелин"] },
      { n: "The Rolling Stones", t: "schooler", a: ["роллинг стоунз", "rolling stones"] },
      { n: "Metallica", t: "schooler", a: ["металлика"] },
      { n: "AC/DC", t: "schooler", a: ["эйси диси", "acdc"] },
      { n: "Radiohead", t: "schooler", a: ["радиохед"] },
      { n: "Кино", t: "schooler" },
      { n: "Deep Purple", t: "schooler", a: ["дип перпл"] },
      { n: "Aerosmith", t: "schooler", a: ["аэросмит"] },
      { n: "Guns N' Roses", t: "schooler", a: ["ганз н роузес", "guns n roses"] },
      { n: "U2", t: "schooler", a: ["ю ту"] },
      { n: "Red Hot Chili Peppers", t: "schooler", a: ["ред хот чили пепперс", "rhcp"] },
      { n: "Linkin Park", t: "schooler", a: ["линкин парк"] },
      { n: "Green Day", t: "schooler", a: ["грин дэй"] },
      { n: "The Who", t: "schooler", a: ["зе ху"] },
      { n: "Muse", t: "schooler", a: ["мьюз"] },
      { n: "Scorpions", t: "schooler", a: ["скорпионс"] },
      { n: "Наутилус Помпилиус", t: "schooler", a: ["наутилус"] },
      { n: "ДДТ", t: "schooler" },
      { n: "Аквариум", t: "schooler" },
      { n: "Алиса", t: "schooler" },
      { n: "Ария", t: "schooler" },
      { n: "The Doors", t: "rare", a: ["дорз", "doors"] },
      { n: "Black Sabbath", t: "rare", a: ["блэк саббат"] },
      { n: "The Cure", t: "rare", a: ["кьюр", "cure"] },
      { n: "Joy Division", t: "rare", a: ["джой дивижн"] },
      { n: "Rush", t: "rare", a: ["раш"] },
      { n: "Motörhead", t: "rare", a: ["моторхед", "motorhead"] },
      { n: "Pixies", t: "rare", a: ["пиксиз"] },
      { n: "Iron Maiden", t: "rare", a: ["айрон мейден"] },
      { n: "Judas Priest", t: "rare", a: ["джудас прист"] },
      { n: "The Clash", t: "rare", a: ["клэш", "clash"] },
      { n: "Ramones", t: "rare", a: ["рамонес"] },
      { n: "Sex Pistols", t: "rare", a: ["секс пистолз"] },
      { n: "Talking Heads", t: "rare", a: ["токинг хэдс"] },
      { n: "Sonic Youth", t: "rare", a: ["соник юс"] },
      { n: "King Crimson", t: "rare", a: ["кинг кримсон"] },
      { n: "Oasis", t: "rare", a: ["оазис"] },
      { n: "Pearl Jam", t: "rare", a: ["перл джем"] },
      { n: "Soundgarden", t: "rare", a: ["саундгарден"] },
      { n: "Can", t: "deepcut", a: ["кан"] },
      { n: "Neu!", t: "deepcut", a: ["ной", "neu"] },
      { n: "Television", t: "deepcut", a: ["телевижн"] },
      { n: "Wire", t: "deepcut", a: ["уайр"] },
      { n: "Slint", t: "deepcut", a: ["слинт"] },
      { n: "Swans", t: "deepcut", a: ["свонс"] },
      { n: "Magazine", t: "deepcut" },
      { n: "Hawkwind", t: "deepcut", a: ["хоквинд"] },
      { n: "Van der Graaf Generator", t: "deepcut", a: ["ван дер грааф"] },
      { n: "This Heat", t: "deepcut", a: ["зис хит"] },
      { n: "The Fall", t: "deepcut", a: ["фолл"] },
      { n: "Shellac", t: "deepcut", a: ["шеллак"] },
      { n: "Гражданская оборона", t: "deepcut", a: ["гроб"] },
      { n: "Аукцыон", t: "deepcut" },
      { n: "Звуки Му", t: "deepcut" },
      { n: "Faust", t: "krillion", a: ["фауст"] },
    ],
  },
  {
    id: "potter",
    text: "Назови персонажа «Гарри Поттера»",
    placeholder: "назови персонажа…",
    answers: [
      { n: "Гарри Поттер", t: "plankton", a: ["гарри"] },
      { n: "Гермиона", t: "plankton", a: ["гермиона грейнджер"] },
      { n: "Рон Уизли", t: "plankton", a: ["рон"] },
      { n: "Дамблдор", t: "tooclever", a: ["альбус дамблдор"] },
      { n: "Волан-де-Морт", t: "tooclever", a: ["волдеморт", "воландеморт"] },
      { n: "Снегг", t: "tooclever", a: ["снейп", "северус снейп", "северус снегг"] },
      { n: "Хагрид", t: "schooler" },
      { n: "Драко Малфой", t: "schooler", a: ["драко"] },
      { n: "Сириус Блэк", t: "schooler", a: ["сириус"] },
      { n: "Луна Лавгуд", t: "schooler", a: ["полумна лавгуд", "полумна"] },
      { n: "Невилл Долгопупс", t: "schooler", a: ["невилл", "невилл лонгботтом"] },
      { n: "Макгонагалл", t: "schooler", a: ["минерва макгонагалл"] },
      { n: "Добби", t: "schooler" },
      { n: "Джинни Уизли", t: "schooler", a: ["джинни"] },
      { n: "Дадли Дурсль", t: "schooler", a: ["дадли"] },
      { n: "Том Реддл", t: "schooler", a: ["реддл"] },
      { n: "Букля", t: "schooler", a: ["хедвига"] },
      { n: "Беллатриса Лестрейндж", t: "rare", a: ["беллатриса"] },
      { n: "Римус Люпин", t: "rare", a: ["люпин"] },
      { n: "Аластор Грюм", t: "rare", a: ["грозный глаз грюм", "грюм"] },
      { n: "Долорес Амбридж", t: "rare", a: ["амбридж"] },
      { n: "Седрик Диггори", t: "rare", a: ["седрик"] },
      { n: "Флёр Делакур", t: "rare", a: ["флер делакур"] },
      { n: "Люциус Малфой", t: "rare", a: ["люциус"] },
      { n: "Виктор Крам", t: "rare", a: ["крам"] },
      { n: "Чжоу Чанг", t: "rare" },
      { n: "Оливер Вуд", t: "rare" },
      { n: "Фред Уизли", t: "rare", a: ["фред"] },
      { n: "Джордж Уизли", t: "rare", a: ["джордж"] },
      { n: "Молли Уизли", t: "rare", a: ["молли"] },
      { n: "Гораций Слизнорт", t: "rare", a: ["слизнорт"] },
      { n: "Клювокрыл", t: "rare" },
      { n: "Гриндевальд", t: "rare" },
      { n: "Аргус Филч", t: "deepcut", a: ["филч"] },
      { n: "Сивилла Трелони", t: "deepcut", a: ["трелони"] },
      { n: "Корнелиус Фадж", t: "deepcut", a: ["фадж"] },
      { n: "Златопуст Локонс", t: "deepcut", a: ["гилдерой локхарт", "локонс"] },
      { n: "Питер Петтигрю", t: "deepcut", a: ["петтигрю", "хвост"] },
      { n: "Нимфадора Тонкс", t: "deepcut", a: ["тонкс"] },
      { n: "Рита Скитер", t: "deepcut", a: ["скитер"] },
      { n: "Кингсли Бруствер", t: "deepcut", a: ["бруствер"] },
      { n: "Филиус Флитвик", t: "deepcut", a: ["флитвик"] },
      { n: "Помона Стебль", t: "deepcut", a: ["стебль"] },
      { n: "Плакса Миртл", t: "deepcut", a: ["миртл"] },
      { n: "Пивз", t: "deepcut" },
      { n: "Кикимер", t: "deepcut", a: ["кричер"] },
      { n: "Ксенофилиус Лавгуд", t: "deepcut", a: ["ксенофилиус"] },
      { n: "Игорь Каркаров", t: "deepcut", a: ["каркаров"] },
      { n: "Мадам Максим", t: "deepcut" },
      { n: "Аберфорт Дамблдор", t: "deepcut", a: ["аберфорт"] },
      { n: "Наземникус Флетчер", t: "deepcut", a: ["наземникус", "мундунгус"] },
      { n: "Квиррелл", t: "deepcut", a: ["квирелл"] },
      { n: "Мадам Помфри", t: "deepcut", a: ["помфри"] },
      { n: "Стэн Шанпайк", t: "krillion", a: ["шанпайк"] },
    ],
  },
  {
    id: "superhero",
    text: "Назови супергероя",
    placeholder: "назови супергероя…",
    answers: [
      { n: "Супермен", t: "plankton" },
      { n: "Человек-паук", t: "plankton", a: ["человек паук", "спайдермен"] },
      { n: "Бэтмен", t: "plankton" },
      { n: "Дэдпул", t: "tooclever" },
      { n: "Железный человек", t: "tooclever", a: ["айрон мэн"] },
      { n: "Тор", t: "schooler" },
      { n: "Халк", t: "schooler" },
      { n: "Капитан Америка", t: "schooler" },
      { n: "Чудо-женщина", t: "schooler", a: ["чудо женщина", "вандер вумен"] },
      { n: "Флэш", t: "schooler" },
      { n: "Росомаха", t: "schooler" },
      { n: "Чёрная вдова", t: "schooler", a: ["черная вдова"] },
      { n: "Аквамен", t: "schooler" },
      { n: "Соколиный глаз", t: "schooler" },
      { n: "Человек-муравей", t: "schooler", a: ["человек муравей"] },
      { n: "Доктор Стрэндж", t: "schooler", a: ["доктор стрендж"] },
      { n: "Чёрная Пантера", t: "schooler", a: ["черная пантера"] },
      { n: "Капитан Марвел", t: "schooler" },
      { n: "Зелёный Фонарь", t: "schooler", a: ["зеленый фонарь"] },
      { n: "Робин", t: "schooler" },
      { n: "Сорвиголова", t: "rare", a: ["мэтт мердок"] },
      { n: "Женщина-Халк", t: "rare", a: ["женщина халк"] },
      { n: "Люк Кейдж", t: "rare" },
      { n: "Джессика Джонс", t: "rare" },
      { n: "Алая Ведьма", t: "rare", a: ["алая ведьма ванда", "ванда максимофф"] },
      { n: "Ртуть", t: "rare" },
      { n: "Вижен", t: "rare", a: ["вижн"] },
      { n: "Циклоп", t: "rare" },
      { n: "Джин Грей", t: "rare" },
      { n: "Шторм", t: "rare" },
      { n: "Колосс", t: "rare" },
      { n: "Ночной Змей", t: "rare" },
      { n: "Серебряный Сёрфер", t: "rare", a: ["серебряный серфер"] },
      { n: "Мистер Фантастик", t: "rare" },
      { n: "Женщина-невидимка", t: "rare", a: ["женщина невидимка"] },
      { n: "Человек-факел", t: "rare", a: ["человек факел"] },
      { n: "Зелёная Стрела", t: "rare", a: ["зеленая стрела"] },
      { n: "Марсианский охотник", t: "deepcut" },
      { n: "Лунный рыцарь", t: "deepcut" },
      { n: "Синий Жук", t: "deepcut" },
      { n: "Красный Торнадо", t: "deepcut" },
      { n: "Плащ и Кинжал", t: "deepcut" },
      { n: "Стальной Кулак", t: "deepcut", a: ["железный кулак"] },
      { n: "Зверь-Бой", t: "deepcut", a: ["зверь бой", "бистбой"] },
      { n: "Ворон", t: "deepcut" },
      { n: "Киборг", t: "deepcut" },
      { n: "Затанна", t: "deepcut" },
      { n: "Пластикмен", t: "deepcut" },
      { n: "Человек-ястреб", t: "deepcut", a: ["человек ястреб"] },
      { n: "Чёрная Канарейка", t: "deepcut", a: ["черная канарейка"] },
      { n: "Мисс Марвел", t: "deepcut" },
      { n: "Мистер Чудо", t: "krillion" },
    ],
  },
  {
    id: "syr",
    text: "Назови сыр",
    placeholder: "назови сыр…",
    answers: [
      { n: "Моцарелла", t: "plankton" },
      { n: "Пармезан", t: "plankton" },
      { n: "Чеддер", t: "tooclever" },
      { n: "Дор блю", t: "tooclever", a: ["дорблю"] },
      { n: "Бри", t: "schooler" },
      { n: "Камамбер", t: "schooler" },
      { n: "Фета", t: "schooler" },
      { n: "Маскарпоне", t: "schooler" },
      { n: "Рикотта", t: "schooler" },
      { n: "Гауда", t: "schooler" },
      { n: "Сулугуни", t: "schooler" },
      { n: "Эдам", t: "schooler" },
      { n: "Брынза", t: "schooler" },
      { n: "Адыгейский", t: "schooler" },
      { n: "Российский", t: "schooler" },
      { n: "Чечил", t: "schooler", a: ["косичка"] },
      { n: "Горгонзола", t: "schooler" },
      { n: "Буррата", t: "rare", a: ["бурата"] },
      { n: "Страчателла", t: "rare" },
      { n: "Скаморца", t: "rare" },
      { n: "Проволоне", t: "rare" },
      { n: "Грана Падано", t: "rare" },
      { n: "Рокфор", t: "rare" },
      { n: "Грюйер", t: "rare" },
      { n: "Эмменталь", t: "rare" },
      { n: "Манчего", t: "rare" },
      { n: "Пекорино", t: "rare" },
      { n: "Халуми", t: "rare" },
      { n: "Стилтон", t: "rare" },
      { n: "Пошехонский", t: "rare" },
      { n: "Раклет", t: "rare" },
      { n: "Конте", t: "deepcut", a: ["комте"] },
      { n: "Реблошон", t: "deepcut" },
      { n: "Тет-де-Муан", t: "deepcut", a: ["тет де муан"] },
      { n: "Морбье", t: "deepcut" },
      { n: "Мюнстер", t: "deepcut" },
      { n: "Таледжо", t: "deepcut" },
      { n: "Кабралес", t: "deepcut" },
      { n: "Эпуасс", t: "deepcut" },
      { n: "Ливаро", t: "deepcut" },
      { n: "Мимолет", t: "deepcut" },
      { n: "Канталь", t: "deepcut" },
      { n: "Бофор", t: "deepcut" },
      { n: "Аппенцеллер", t: "deepcut" },
      { n: "Азиаго", t: "deepcut" },
      { n: "Вьё-Булонь", t: "krillion", a: ["вье булонь"] },
    ],
  },
  {
    id: "dinozavr",
    text: "Назови динозавра",
    placeholder: "назови динозавра…",
    answers: [
      { n: "Тираннозавр", t: "plankton", a: ["тирекс", "ти рекс", "тираннозавр рекс"] },
      { n: "Трицератопс", t: "plankton" },
      { n: "Велоцираптор", t: "tooclever", a: ["раптор"] },
      { n: "Стегозавр", t: "tooclever" },
      { n: "Брахиозавр", t: "schooler" },
      { n: "Диплодок", t: "schooler" },
      { n: "Аллозавр", t: "schooler" },
      { n: "Анкилозавр", t: "schooler" },
      { n: "Спинозавр", t: "schooler" },
      { n: "Игуанодон", t: "schooler" },
      { n: "Паразауролоф", t: "schooler" },
      { n: "Апатозавр", t: "schooler", a: ["бронтозавр"] },
      { n: "Археоптерикс", t: "schooler" },
      { n: "Карнотавр", t: "rare" },
      { n: "Дейноних", t: "rare" },
      { n: "Пахицефалозавр", t: "rare" },
      { n: "Компсогнат", t: "rare" },
      { n: "Теризинозавр", t: "rare" },
      { n: "Овираптор", t: "rare" },
      { n: "Гиганотозавр", t: "rare", a: ["гигантозавр"] },
      { n: "Аргентинозавр", t: "rare" },
      { n: "Тарбозавр", t: "rare" },
      { n: "Протоцератопс", t: "rare" },
      { n: "Микрораптор", t: "rare" },
      { n: "Утараптор", t: "rare" },
      { n: "Целофизис", t: "rare" },
      { n: "Галлимим", t: "rare" },
      { n: "Майязавра", t: "deepcut" },
      { n: "Гипсилофодон", t: "deepcut" },
      { n: "Троодон", t: "deepcut" },
      { n: "Кентрозавр", t: "deepcut" },
      { n: "Заурофаганакс", t: "deepcut" },
      { n: "Дилофозавр", t: "deepcut" },
      { n: "Барионикс", t: "deepcut" },
      { n: "Стиракозавр", t: "deepcut" },
      { n: "Коритозавр", t: "deepcut" },
      { n: "Эдмонтозавр", t: "deepcut" },
      { n: "Мамэнчизавр", t: "deepcut" },
      { n: "Дейнохейрус", t: "deepcut" },
      { n: "Гетеродонтозавр", t: "deepcut" },
      { n: "Синозавроптерикс", t: "deepcut" },
      { n: "Зауропельта", t: "deepcut" },
      { n: "Микропахицефалозавр", t: "krillion" },
    ],
  },
  {
    id: "muzey",
    text: "Назови известный музей",
    placeholder: "назови музей…",
    answers: [
      { n: "Лувр", t: "plankton" },
      { n: "Эрмитаж", t: "plankton" },
      { n: "Британский музей", t: "tooclever" },
      { n: "Метрополитен", t: "tooclever", a: ["музей метрополитен"] },
      { n: "Прадо", t: "schooler" },
      { n: "Уффици", t: "schooler" },
      { n: "Ватиканские музеи", t: "schooler", a: ["ватиканский музей"] },
      { n: "Третьяковская галерея", t: "schooler", a: ["третьяковка"] },
      { n: "Музей Ван Гога", t: "schooler" },
      { n: "Рейксмузеум", t: "schooler" },
      { n: "Орсе", t: "schooler", a: ["музей орсе"] },
      { n: "Гуггенхайм", t: "schooler", a: ["музей гуггенхайма"] },
      { n: "Центр Помпиду", t: "schooler", a: ["помпиду"] },
      { n: "Тейт Модерн", t: "schooler", a: ["тейт"] },
      { n: "Русский музей", t: "schooler" },
      { n: "МоМА", t: "rare", a: ["мома", "музей современного искусства"] },
      { n: "Пергамский музей", t: "rare" },
      { n: "Музей Виктории и Альберта", t: "rare" },
      { n: "Кунсткамера", t: "rare" },
      { n: "Лондонская национальная галерея", t: "rare", a: ["национальная галерея"] },
      { n: "Пушкинский музей", t: "rare", a: ["гмии", "пушкинский"] },
      { n: "Дрезденская галерея", t: "rare" },
      { n: "Старая пинакотека", t: "rare", a: ["пинакотека"] },
      { n: "Галерея Академии", t: "rare" },
      { n: "Египетский музей", t: "rare" },
      { n: "Смитсоновский институт", t: "rare", a: ["смитсоновский музей"] },
      { n: "Институт искусств Чикаго", t: "rare" },
      { n: "Музей Акрополя", t: "rare" },
      { n: "Маурицхёйс", t: "deepcut", a: ["маурицхейс"] },
      { n: "Музей Гетти", t: "deepcut", a: ["гетти"] },
      { n: "Музей Ашмола", t: "deepcut", a: ["ашмолеан"] },
      { n: "Альбертина", t: "deepcut" },
      { n: "Галерея Боргезе", t: "deepcut", a: ["боргезе"] },
      { n: "Музей Соане", t: "deepcut" },
      { n: "Музей Тиссена-Борнемисы", t: "deepcut", a: ["тиссена борнемисы"] },
      { n: "Музей Изабеллы Стюарт Гарднер", t: "krillion" },
    ],
  },
  {
    id: "gaz",
    text: "Назови химический элемент, который при комнатной температуре — газ",
    placeholder: "назови элемент…",
    // Полный список: при 20 °C газообразны ровно одиннадцать элементов.
    exhaustive: true,
    answers: [
      { n: "Кислород", t: "plankton" },
      { n: "Водород", t: "plankton" },
      { n: "Азот", t: "tooclever" },
      { n: "Гелий", t: "tooclever" },
      { n: "Хлор", t: "schooler" },
      { n: "Неон", t: "schooler" },
      { n: "Аргон", t: "schooler" },
      { n: "Фтор", t: "rare" },
      { n: "Криптон", t: "rare" },
      { n: "Ксенон", t: "deepcut" },
      { n: "Радон", t: "krillion" },
    ],
  },
  {
    id: "ptica",
    text: "Назови нелетающую птицу",
    placeholder: "назови птицу…",
    answers: [
      { n: "Пингвин", t: "plankton" },
      { n: "Страус", t: "plankton" },
      { n: "Дронт", t: "tooclever", a: ["додо"] },
      { n: "Киви", t: "tooclever" },
      { n: "Эму", t: "schooler" },
      { n: "Казуар", t: "schooler" },
      { n: "Нанду", t: "schooler" },
      { n: "Какапо", t: "rare", a: ["совиный попугай"] },
      { n: "Моа", t: "rare" },
      { n: "Пароходная утка", t: "rare" },
      { n: "Галапагосский баклан", t: "rare", a: ["нелетающий баклан"] },
      { n: "Казуар-мурук", t: "rare", a: ["мурук"] },
      { n: "Такахе", t: "deepcut" },
      { n: "Уэка", t: "deepcut" },
      { n: "Бескрылая гагарка", t: "deepcut" },
      { n: "Эпиорнис", t: "deepcut", a: ["слоновая птица"] },
      { n: "Кагу", t: "deepcut" },
      { n: "Гуамский пастушок", t: "deepcut" },
      { n: "Кампбельский чирок", t: "deepcut" },
      { n: "Оклендский чирок", t: "deepcut" },
      { n: "Лайсанский пастушок", t: "deepcut" },
      { n: "Гавайский пастушок", t: "deepcut" },
      { n: "Дронт-отшельник", t: "deepcut", a: ["родригесский дронт"] },
      { n: "Титикакская поганка", t: "deepcut" },
      { n: "Гасторнис", t: "deepcut" },
      { n: "Фороракос", t: "deepcut" },
      { n: "Стефенский крапивник", t: "krillion" },
      { n: "Тристанский пастушок", t: "krillion" },
    ],
  },
  {
    id: "sous",
    text: "Назови соус или дип",
    placeholder: "назови соус…",
    answers: [
      { n: "Кетчуп", t: "plankton" },
      { n: "Майонез", t: "plankton" },
      { n: "Горчица", t: "tooclever" },
      { n: "Соевый соус", t: "tooclever", a: ["соевый"] },
      { n: "Ткемали", t: "schooler" },
      { n: "Аджика", t: "schooler" },
      { n: "Тартар", t: "schooler" },
      { n: "Бешамель", t: "schooler" },
      { n: "Песто", t: "schooler" },
      { n: "Барбекю", t: "schooler", a: ["соус барбекю", "ббq"] },
      { n: "Сальса", t: "schooler" },
      { n: "Цезарь", t: "schooler" },
      { n: "Табаско", t: "schooler" },
      { n: "Гуакамоле", t: "schooler" },
      { n: "Хумус", t: "schooler" },
      { n: "Цацики", t: "rare", a: ["дзадзики"] },
      { n: "Айоли", t: "rare" },
      { n: "Харисса", t: "rare" },
      { n: "Терияки", t: "rare" },
      { n: "Шрирача", t: "rare" },
      { n: "Вустерский соус", t: "rare", a: ["вустерширский соус"] },
      { n: "Голландский соус", t: "rare", a: ["голландез"] },
      { n: "Маринара", t: "rare" },
      { n: "Болоньезе", t: "rare" },
      { n: "Ранч", t: "rare" },
      { n: "Хойсин", t: "rare" },
      { n: "Тахини", t: "rare" },
      { n: "Сацебели", t: "rare" },
      { n: "Наршараб", t: "rare" },
      { n: "Чимичурри", t: "deepcut" },
      { n: "Ромеско", t: "deepcut" },
      { n: "Демиглас", t: "deepcut", a: ["деми глас"] },
      { n: "Велюте", t: "deepcut" },
      { n: "Понзу", t: "deepcut" },
      { n: "Беарнский соус", t: "deepcut", a: ["беарнез"] },
      { n: "Грибиш", t: "deepcut" },
      { n: "Равигот", t: "deepcut" },
      { n: "Субиз", t: "deepcut" },
      { n: "Бордолез", t: "deepcut" },
      { n: "Скордаля", t: "krillion" },
    ],
  },
  {
    id: "instrument",
    text: "Назови музыкальный инструмент",
    placeholder: "назови инструмент…",
    answers: [
      { n: "Гитара", t: "plankton" },
      { n: "Пианино", t: "plankton", a: ["фортепиано", "рояль"] },
      { n: "Скрипка", t: "tooclever" },
      { n: "Барабан", t: "tooclever", a: ["барабаны", "ударные"] },
      { n: "Флейта", t: "schooler" },
      { n: "Саксофон", t: "schooler" },
      { n: "Аккордеон", t: "schooler" },
      { n: "Балалайка", t: "schooler" },
      { n: "Виолончель", t: "schooler" },
      { n: "Труба", t: "schooler" },
      { n: "Контрабас", t: "schooler" },
      { n: "Кларнет", t: "schooler" },
      { n: "Тромбон", t: "schooler" },
      { n: "Орган", t: "schooler" },
      { n: "Синтезатор", t: "schooler" },
      { n: "Укулеле", t: "schooler" },
      { n: "Банджо", t: "schooler" },
      { n: "Мандолина", t: "schooler" },
      { n: "Гармонь", t: "schooler" },
      { n: "Арфа", t: "rare" },
      { n: "Гобой", t: "rare" },
      { n: "Фагот", t: "rare" },
      { n: "Валторна", t: "rare" },
      { n: "Туба", t: "rare" },
      { n: "Альт", t: "rare" },
      { n: "Баян", t: "rare" },
      { n: "Терменвокс", t: "rare" },
      { n: "Ситар", t: "rare" },
      { n: "Цимбалы", t: "rare" },
      { n: "Волынка", t: "rare" },
      { n: "Ксилофон", t: "rare" },
      { n: "Литавры", t: "rare" },
      { n: "Маримба", t: "rare" },
      { n: "Табла", t: "rare" },
      { n: "Диджериду", t: "rare" },
      { n: "Челеста", t: "deepcut" },
      { n: "Клавесин", t: "deepcut" },
      { n: "Кото", t: "deepcut" },
      { n: "Дудук", t: "deepcut" },
      { n: "Варган", t: "deepcut" },
      { n: "Никельхарпа", t: "deepcut" },
      { n: "Сямисэн", t: "deepcut" },
      { n: "Эрху", t: "deepcut" },
      { n: "Бандонеон", t: "deepcut" },
      { n: "Фисгармония", t: "deepcut" },
      { n: "Калимба", t: "deepcut" },
      { n: "Зурна", t: "deepcut" },
      { n: "Хардангерфеле", t: "krillion" },
    ],
  },
  {
    id: "strana_zvezda",
    text: "Назови страну, у которой на флаге есть звезда",
    placeholder: "назови страну…",
    answers: [
      { n: "США", t: "plankton", a: ["сша", "америка"] },
      { n: "Китай", t: "plankton" },
      { n: "Турция", t: "tooclever" },
      { n: "Вьетнам", t: "tooclever" },
      { n: "Бразилия", t: "schooler" },
      { n: "Австралия", t: "schooler" },
      { n: "Новая Зеландия", t: "schooler" },
      { n: "Куба", t: "schooler" },
      { n: "Марокко", t: "schooler" },
      { n: "Чили", t: "schooler" },
      { n: "Израиль", t: "schooler" },
      { n: "Северная Корея", t: "schooler", a: ["кндр"] },
      { n: "Азербайджан", t: "schooler" },
      { n: "Узбекистан", t: "schooler" },
      { n: "Малайзия", t: "schooler" },
      { n: "Тунис", t: "schooler" },
      { n: "Алжир", t: "schooler" },
      { n: "Пакистан", t: "rare" },
      { n: "Сингапур", t: "rare" },
      { n: "Панама", t: "rare" },
      { n: "Сомали", t: "rare" },
      { n: "Сенегал", t: "rare" },
      { n: "Мьянма", t: "rare" },
      { n: "Филиппины", t: "rare" },
      { n: "Венесуэла", t: "rare" },
      { n: "Гондурас", t: "rare" },
      { n: "Либерия", t: "rare" },
      { n: "Гана", t: "rare" },
      { n: "Камерун", t: "rare" },
      { n: "Того", t: "rare" },
      { n: "Мавритания", t: "rare" },
      { n: "Ливия", t: "rare" },
      { n: "Сирия", t: "rare" },
      { n: "Иордания", t: "rare" },
      { n: "Туркменистан", t: "rare" },
      { n: "Мозамбик", t: "rare" },
      { n: "Зимбабве", t: "rare" },
      { n: "Кабо-Верде", t: "deepcut", a: ["кабо верде"] },
      { n: "Коморы", t: "deepcut" },
      { n: "Науру", t: "deepcut" },
      { n: "Тувалу", t: "deepcut" },
      { n: "Бурунди", t: "deepcut" },
      { n: "Джибути", t: "deepcut" },
      { n: "Буркина-Фасо", t: "deepcut", a: ["буркина фасо"] },
      { n: "Гвинея-Бисау", t: "deepcut", a: ["гвинея бисау"] },
      { n: "ЦАР", t: "deepcut", a: ["центральноафриканская республика"] },
      { n: "Микронезия", t: "deepcut" },
      { n: "Маршалловы Острова", t: "deepcut" },
      { n: "Соломоновы Острова", t: "deepcut" },
      { n: "Самоа", t: "deepcut" },
      { n: "Босния и Герцеговина", t: "deepcut", a: ["босния"] },
      { n: "Сан-Томе и Принсипи", t: "krillion", a: ["сан томе и принсипи"] },
    ],
  },
  {
    id: "nastolka",
    text: "Назови настольную игру",
    placeholder: "назови игру…",
    answers: [
      { n: "Монополия", t: "plankton" },
      { n: "Шахматы", t: "plankton" },
      { n: "Шашки", t: "tooclever" },
      { n: "Мафия", t: "tooclever" },
      { n: "Нарды", t: "schooler" },
      { n: "Уно", t: "schooler" },
      { n: "Дженга", t: "schooler" },
      { n: "Скрэббл", t: "schooler", a: ["эрудит"] },
      { n: "Каркассон", t: "schooler" },
      { n: "Домино", t: "schooler" },
      { n: "Лото", t: "schooler" },
      { n: "Твистер", t: "schooler" },
      { n: "Морской бой", t: "schooler" },
      { n: "Активити", t: "schooler" },
      { n: "Дурак", t: "schooler" },
      { n: "Го", t: "rare" },
      { n: "Колонизаторы", t: "rare", a: ["катан"] },
      { n: "Диксит", t: "rare" },
      { n: "Билет на поезд", t: "rare" },
      { n: "Кодовые имена", t: "rare", a: ["коднеймс"] },
      { n: "Пандемия", t: "rare" },
      { n: "Сплендор", t: "rare" },
      { n: "Клюдо", t: "rare", a: ["клуэдо"] },
      { n: "Риск", t: "rare" },
      { n: "Манчкин", t: "rare" },
      { n: "Бэнг", t: "rare" },
      { n: "Сёгун", t: "rare", a: ["сёги", "сеги"] },
      { n: "Агрикола", t: "deepcut" },
      { n: "Пуэрто-Рико", t: "deepcut", a: ["пуэрто рико"] },
      { n: "Твилайт Империум", t: "deepcut" },
      { n: "Через века", t: "deepcut" },
      { n: "Рэндзю", t: "deepcut", a: ["гомоку"] },
      { n: "Гвинт", t: "deepcut" },
      { n: "Брасс", t: "deepcut" },
      { n: "Терраформирование Марса", t: "deepcut" },
      { n: "Тафл", t: "krillion", a: ["хнефатафл"] },
    ],
  },
  {
    id: "sputnik",
    text: "Назови спутник планеты Солнечной системы",
    placeholder: "назови спутник…",
    // Только спутники планет: у карликовых (Плутон и прочие) не считается.
    answers: [
      { n: "Луна", t: "plankton" },
      { n: "Европа", t: "tooclever" },
      { n: "Титан", t: "tooclever" },
      { n: "Ио", t: "schooler" },
      { n: "Ганимед", t: "schooler" },
      { n: "Каллисто", t: "schooler" },
      { n: "Фобос", t: "schooler" },
      { n: "Деймос", t: "schooler" },
      { n: "Энцелад", t: "rare" },
      { n: "Тритон", t: "rare" },
      { n: "Титания", t: "rare" },
      { n: "Оберон", t: "rare" },
      { n: "Миранда", t: "rare" },
      { n: "Мимас", t: "rare" },
      { n: "Рея", t: "rare" },
      { n: "Япет", t: "rare" },
      { n: "Диона", t: "deepcut" },
      { n: "Тефия", t: "deepcut", a: ["тефида"] },
      { n: "Умбриэль", t: "deepcut" },
      { n: "Ариэль", t: "deepcut" },
      { n: "Гиперион", t: "deepcut" },
      { n: "Феба", t: "deepcut" },
      { n: "Нереида", t: "deepcut" },
      { n: "Протей", t: "deepcut" },
      { n: "Янус", t: "deepcut" },
      { n: "Эпиметей", t: "deepcut" },
      { n: "Телесто", t: "deepcut" },
      { n: "Сикоракса", t: "deepcut" },
      { n: "Таласса", t: "krillion" },
    ],
  },
];
